# Generated by Django 4.1.1 on 2022-10-04 02:56

from django.db import migrations


def populate_status(apps, schemaeditor):
    statuses = {
        "To Do": "An issue that hasn't been started",
        "In Progress": "An issues that is being worked on",
        "Done": "An issue that has been resolved"
    }
    Status = apps.get_model("issues", "Status")
    for key, desc in statuses.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [migrations.RunPython(populate_status)]
